// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmOqzlxM8cPtU8uBeFx28O7-KGn0BtIho',
    appId: '1:183950402704:web:a0b94a6ce30902fe0be415',
    messagingSenderId: '183950402704',
    projectId: 'katalog-kue',
    authDomain: 'katalog-kue.firebaseapp.com',
    storageBucket: 'katalog-kue.firebasestorage.app',
    measurementId: 'G-907GSFSM47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgoS7bz7iM_HUaE8TjNtpl_8DImcrIuu0',
    appId: '1:183950402704:android:4c37b7faef123ae30be415',
    messagingSenderId: '183950402704',
    projectId: 'katalog-kue',
    storageBucket: 'katalog-kue.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpOhB7j-h-ET7PAo1XGNfIlhq4W2CIcfs',
    appId: '1:183950402704:ios:19f34c489ee60aa60be415',
    messagingSenderId: '183950402704',
    projectId: 'katalog-kue',
    storageBucket: 'katalog-kue.firebasestorage.app',
    iosBundleId: 'com.example.katalogKueLebaran',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmOqzlxM8cPtU8uBeFx28O7-KGn0BtIho',
    appId: '1:183950402704:web:85370d0af1af83dd0be415',
    messagingSenderId: '183950402704',
    projectId: 'katalog-kue',
    authDomain: 'katalog-kue.firebaseapp.com',
    storageBucket: 'katalog-kue.firebasestorage.app',
    measurementId: 'G-NJV9B9JSQT',
  );
}
